source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               web/,\
               lib/,\
               plugin_zh.properties,\
               plugin.properties
