view.name=Terminal
view.category.name=Terminal
preference.page.name=Terminal
preference.page.theme.name=Terminal Themes
command.openInTerminal.name=Open in Terminal
command.openInTerminal.label=Open in Terminal
toolbar.terminal.label=Terminal
command.launchToolbar.label=Launch Terminal
command.launchToolbar.tooltip=Launch a new terminal instance